apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-demo-deployment
  labels:
    app: helloworld-demo-python
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld-demo-python
  template:
    metadata:
      labels:
        app: helloworld-demo-python
    spec:
      containers:
      - name: helloworld-demo-python
        image: deepikaadeepi01/helloworld-demo-python:v1
        ports:
        - containerPort: 8080
